### ISSUE TITLE
Switch to GitHub Actions for CI

### ISSUE THREAD

**Issue by michaelherold** [michaelherold/benchmark-memory#14]
Travis is being really slow lately so I think it's time to move.

Things that I would like to see:

1. Test failures block the build and run on the current Travis matrix
2. Linting failures (i.e. Rubocop) block the build and run once

(@AlexWayfer mentioned being interested in this, but if someone else wants to do it, I'm open to that.)

**Comment by AlexWayfer** [comment]
I think, you can assign this to me, I'm ready to try to help.

**Comment by AlexWayfer** [comment]
I'm going to remove `codeclimate-test-reporter` because I see no test coverage: https://codeclimate.com/github/michaelherold/benchmark-memory

![image](https://user-images.githubusercontent.com/6510020/100395782-48fea980-3053-11eb-98d5-4fa5cad788fd.png)

Also I don't see coverage badge in the README.

I suggest to use something like [Codecov](https://codecov.io/) in the future.

**Comment by AlexWayfer** [comment]
I've faced with https://github.community/t/support-for-yaml-anchors/16128

So, a config for Cirrus CI can be more compact, like this:

```yaml
bundle_cache: &bundle_cache
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat *.gemspec
  install_script:
    - gem install bundler
    - bundle update

rubocop_task:
  container:
    image: ruby:latest
  <<: *bundle_cache

  lint_script: bundle exec rubocop

test_task:
  container:
    matrix:
      image: ruby:2.4
      image: ruby:2.5
      image: ruby:2.6
      image: ruby:2.7
  <<: *bundle_cache

  test_script: bundle exec rspec
```

But… as you wish.
